// <auto-generated />
using System;
using MessengerInfrastructure.MessageContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessengerInfrastructure.Migrations
{
    [DbContext(typeof(MessageDbContext))]
    [Migration("20221018143049_testing_seeding_with_loop")]
    partial class testing_seeding_with_loop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessengerInfrastructure.Entity.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Message", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Attachment = "Attachments",
                            CreatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5879),
                            From = "TestFrom@gmail.com",
                            FromName = "FromName",
                            IsDeleted = false,
                            Message = "Message",
                            Title = "Title",
                            To = "testTo@gmail.com",
                            ToName = "ToName",
                            UpdatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5880)
                        },
                        new
                        {
                            Id = 11,
                            Attachment = "11Attachments",
                            CreatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5884),
                            From = "11TestFrom@gmail.com",
                            FromName = "11FromName",
                            IsDeleted = false,
                            Message = "11Message",
                            Title = "11Title",
                            To = "11testTo@gmail.com",
                            ToName = "11ToName",
                            UpdatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5884)
                        },
                        new
                        {
                            Id = 12,
                            Attachment = "12Attachments",
                            CreatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5887),
                            From = "12TestFrom@gmail.com",
                            FromName = "12FromName",
                            IsDeleted = false,
                            Message = "12Message",
                            Title = "12Title",
                            To = "12testTo@gmail.com",
                            ToName = "12ToName",
                            UpdatedDate = new DateTime(2022, 10, 18, 14, 30, 49, 550, DateTimeKind.Utc).AddTicks(5888)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
